import { Member, MaritalStatus, Sector, Role } from './types';

export const INITIAL_MEMBERS: Member[] = [
    {
        id: 1,
        photo: '',
        fullName: 'João da Silva e Maria da Silva',
        birthDate: '1980-05-15',
        maritalStatus: MaritalStatus.CASADO,
        spouseName: 'Maria da Silva',
        phone: '11987654321',
        email: 'joao.silva@email.com',
        cep: '01001-000',
        street: 'Praça da Sé',
        neighborhood: 'Sé',
        city: 'São Paulo',
        state: 'SP',
        parish: 'Paróquia Catedral da Sé',
        community: 'Comunidade Matriz',
        sector: Sector.CASOS_ESPECIAIS,
        role: Role.COORDENADOR,
        joinDate: '2018-02-10',
        notes: 'Casal coordenador do setor A.'
    },
    {
        id: 2,
        photo: '',
        fullName: 'Carlos Souza',
        birthDate: '1992-11-20',
        maritalStatus: MaritalStatus.SOLTEIRO,
        phone: '21912345678',
        email: 'carlos.souza@email.com',
        cep: '20510-060',
        street: 'Rua Conde de Bonfim',
        neighborhood: 'Tijuca',
        city: 'Rio de Janeiro',
        state: 'RJ',
        parish: 'Paróquia São José',
        community: 'Comunidade São José',
        sector: Sector.PRE_MATRIMONIAL,
        role: Role.AGENTE,
        joinDate: '2022-08-01',
        notes: 'Responsável pelas mídias sociais.'
    },
    {
        id: 3,
        photo: '',
        fullName: 'Ana Pereira',
        birthDate: '1965-03-30',
        maritalStatus: MaritalStatus.VIUVO,
        phone: '31988887777',
        email: 'ana.pereira@email.com',
        cep: '30140-061',
        street: 'Rua Pernambuco',
        neighborhood: 'Funcionários',
        city: 'Belo Horizonte',
        state: 'MG',
        parish: 'Paróquia Santa Rita',
        community: 'Comunidade Santa Rita',
        sector: Sector.POS_MATRIMONIAL,
        role: Role.AGENTE,
        joinDate: '2015-01-20',
        notes: 'Ajuda na organização de eventos.'
    },
];